layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      
projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  website: https://eduline-01.github.io/
  linkedin: sanketbiswas01
  telegram: eduline_01
  discord: 612119361037008906
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: sanket_biswas01
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Coursework
    web_url: https://eduline-01.github.io/course-work
    image_url: https://cdn.startschoolnow.org/wp-content/uploads/Academic-coursework.jpg
    
  - name: Projects
    web_url: https://eduline-01.github.io/my-projects
    image_url: https://scientificwritingtips.files.wordpress.com/2015/05/writingtips-12.jpg
  
  - name: Curriculum Vitae
    web_url: https://drive.google.com/file/d/1cMKkA7HXqHeNS9AN0Z1V3jnTU_NLRcyg/view?usp=sharing
    image_url: https://thumbs.dreamstime.com/b/cartoon-businessman-job-seeker-applicant-holding-curriculum-vitae-cv-resume-cartoon-stick-man-drawing-conceptual-116434870.jpg
    
  - name: Random Thoughts
    web_url: https://eduline-01.github.io/random-thoughts
    image_url: https://image.scoopwhoop.com/w620/s4.scoopwhoop.com/anj/silly/53c90736-5a3f-435c-9f01-0122d494289d.jpg.webp
