layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      
topics:
  - name: Curriculum Vitae
    web_url: https://drive.google.com/file/d/1cMKkA7HXqHeNS9AN0Z1V3jnTU_NLRcyg/view?usp=sharing
    image_url: https://i.pinimg.com/originals/c0/36/22/c0362268e010cd321204de0fe25cb8c0.jpg

  - name: Coursework
    image_url: https://cdn.startschoolnow.org/wp-content/uploads/Academic-coursework.jpg
    
  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png     

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  website: https://eduline-01.github.io/
  linkedin: sanketbiswas01
  telegram: eduline_01
  discord: 612119361037008906
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: sanket_biswas01
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username
